version: "0.1"
services:
  account-service:
    build: ./services/account
    restart: always
    # profiles: ["backend"]
  
  inventory-service:
    build: ./services/inventory
    restart: always
    
  components-service:
    build: ./services/components
    restart: always
    
  ordering-service:
    build: ./services/ordering
    restart: always

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
